version: '3'

services:
  firebox-client:
    build:
      context: ../../
      dockerfile: deployment/client/Dockerfile
    container_name: firebox-client
    ports:
      - "8000:8000"
    volumes:
      - ../../client/server:/app/server
      - ../../client/db:/app/db
      - ../../client/scripts:/app/scripts
      - ../../client/requirements.txt:/app/requirements.txt
      - ../../client/config.py:/app/config.py
      - firebox-data:/app/my_firebox
      - db-data:/app/data
      - chunk-data:/app/tmp/chunk
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - PYTHONPATH=/app
      - APP_DIR=/app
      - SYNC_DIR=/app/my_firebox
      - CHUNK_DIR=/app/tmp/chunk
      - DATABASE_URL=sqlite:///./data/firebox.db
      - DB_FILE_PATH=/app/data/firebox.db
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=10
      - DB_POOL_TIMEOUT=30
      - DB_POOL_RECYCLE=3600
      - CHUNK_SIZE=5242880
      - API_HOST=0.0.0.0
      - API_PORT=8000
      # Files Service API settings
      - FILES_SERVICE_URL=http://files-service:8001
      - REQUEST_TIMEOUT=30
      - MAX_RETRIES=3
    networks:
      - firebox-network
    restart: unless-stopped

volumes:
  firebox-data:
    driver: local
  db-data:
    driver: local
  chunk-data:
    driver: local

networks:
  firebox-network:
    external: true
